import Foundation

enum SpiritSampleData {
    static let trails: [SpiritTrail] = [
        SpiritTrail(mood: .reflective, title: "Reflective Trail", place: "Banff Cedar Forest Walk", minutes: 12, sound: .cedarForest, challenge: "Find something green and photograph its texture.", storyTitle: "Banff National Park", province: "Banff", paletteSeed: 1, imageName: "TrailBanffCedar", difficulty: "Easy", season: "Spring to fall", summary: "A slow cedar-lined reset for noticing shape, shadow, and the mood of mountain air.", routeSteps: ["Start beside the imagined cedar line and set a gentle walking pace.", "Pause after three minutes and notice one green detail without naming it quickly.", "Listen to Cedar Forest sound and match your steps to the softest layer.", "Finish by taking one photo of texture: bark, moss, needles, or stone."]),
        SpiritTrail(mood: .calm, title: "Calm Trail", place: "Lake Louise Shore Reset", minutes: 8, sound: .lakeShore, challenge: "Find one reflection and watch it change.", storyTitle: "A Lake Held by Mountains", province: "Banff", paletteSeed: 2, imageName: "TrailLakeLouise", difficulty: "Easy", season: "All season", summary: "A compact lake-shore walk for settling the nervous system through reflection and horizon lines.", routeSteps: ["Walk as if the water is setting your pace.", "Find one reflected shape and keep it in view for thirty seconds.", "Let the Lake Shore sound become the only timer.", "End with one sentence: what became calmer?"]),
        SpiritTrail(mood: .focused, title: "Focused Trail", place: "Jasper Compass Loop", minutes: 10, sound: .mountainWind, challenge: "Find a natural line pointing north or west.", storyTitle: "Jasper Night Sky", province: "Jasper", paletteSeed: 3, imageName: "TrailJasperCompass", difficulty: "Easy", season: "Clear days", summary: "A clean, directional trail for turning mental noise into one next decision.", routeSteps: ["Choose a direction before you start.", "Walk for five minutes without changing it.", "Find a line: branch, ridge, curb, shadow, or path edge.", "Use the line to choose one small thing you will finish today."]),
        SpiritTrail(mood: .adventurous, title: "Adventure Trail", place: "Yukon Aurora Ridge", minutes: 15, sound: .northernNight, challenge: "Find something older than you and name it.", storyTitle: "Gold Trails and Night Skies", province: "Yukon", paletteSeed: 4, imageName: "TrailYukonAurora", difficulty: "Medium", season: "Cold clear nights", summary: "A brighter, braver route for moving toward unfamiliar details instead of away from them.", routeSteps: ["Begin with Mountain Wind or Northern Night sound.", "Pick the more interesting path within sight.", "Find an old object, surface, or natural feature.", "Give it a title like it belongs in a field journal."]),
        SpiritTrail(mood: .social, title: "Social Trail", place: "Nova Scotia Tide Walk", minutes: 7, sound: .campfire, challenge: "Send one photo to someone who needs a small bright thing.", storyTitle: "Old Railways", province: "Nova Scotia", paletteSeed: 5, imageName: "TrailNovaTide", difficulty: "Easy", season: "Windy days", summary: "A short coastal-style trail for turning a private reset into a gentle shared signal.", routeSteps: ["Walk until you find a color that feels warm.", "Take a photo without overthinking composition.", "Send it with one honest line, not a performance.", "Let Campfire sound close the loop."]),
        SpiritTrail(mood: .calm, title: "Rain Soft Trail", place: "British Columbia Fern Path", minutes: 6, sound: .rainForest, challenge: "Find three different leaves without picking them.", storyTitle: "Coastal Rainforest Memory", province: "British Columbia", paletteSeed: 6, imageName: "TrailBCRainforest", difficulty: "Easy", season: "Rain days", summary: "A damp, green reset for letting attention become softer and more precise.", routeSteps: ["Start under cover or near trees.", "Find three leaves with different edges.", "Listen for a repeating rain rhythm.", "Leave everything exactly where it is."]),
        SpiritTrail(mood: .reflective, title: "Quiet Rail Trail", place: "Kettle Valley Neon Line", minutes: 11, sound: .mountainWind, challenge: "Find a texture that looks like a map.", storyTitle: "Old Railways", province: "British Columbia", paletteSeed: 7, imageName: "TrailKettleRail", difficulty: "Easy", season: "Dry evenings", summary: "A linear walk inspired by old rail grades, made for memory, distance, and perspective.", routeSteps: ["Walk in the straightest safe line available.", "Notice how a line changes your thinking.", "Find a map-like crack, grain, or shadow.", "Name one thing behind you and one thing ahead."]),
        SpiritTrail(mood: .focused, title: "Granite Decision Walk", place: "Yoho Stone Steps", minutes: 9, sound: .cedarForest, challenge: "Find a hard edge and a soft edge.", storyTitle: "Yoho Stone Stories", province: "British Columbia", paletteSeed: 8, imageName: "TrailYohoStone", difficulty: "Easy", season: "All season", summary: "A compact focus trail that uses contrast to make one decision feel less tangled.", routeSteps: ["Find something hard: stone, wall, curb, or packed ground.", "Find something soft: moss, cloud, leaf, or fabric.", "Compare both for ten breaths.", "Choose one decision that needs a harder edge."]),
        SpiritTrail(mood: .adventurous, title: "Remote Lake Signal", place: "Yukon Mirror Shore", minutes: 14, sound: .lakeShore, challenge: "Find a reflection that breaks into pieces.", storyTitle: "Remote Lake Signal", province: "Yukon", paletteSeed: 9, imageName: "TrailRemoteLake", difficulty: "Medium", season: "Summer twilight", summary: "An exploratory route for people who want the day to feel larger without needing a long hike.", routeSteps: ["Look for any reflective surface, even a window.", "Watch it distort when you move.", "Walk until the reflection changes twice.", "Record the most surprising shape."]),
        SpiritTrail(mood: .social, title: "Campfire Circle", place: "Algonquin Ember Loop", minutes: 10, sound: .campfire, challenge: "Ask someone their favorite outdoor smell.", storyTitle: "Beaver Builders", province: "Ontario", paletteSeed: 10, imageName: "TrailCampfireCircle", difficulty: "Easy", season: "Evenings", summary: "A warm, low-pressure social route built around memory, scent, and shared outdoor language.", routeSteps: ["Start with Campfire sound.", "Think of one outdoor smell from childhood.", "Ask someone theirs or write it to them.", "Collect both answers like badges."]),
        SpiritTrail(mood: .calm, title: "Prairie Sky Reset", place: "Saskatchewan Open Horizon", minutes: 5, sound: .mountainWind, challenge: "Find the widest open shape around you.", storyTitle: "Cree Star Knowledge", province: "Prairies", paletteSeed: 11, imageName: "TrailPrairieSky", difficulty: "Easy", season: "Clear skies", summary: "The fastest WN SPRT route: five minutes of horizon-thinking when everything feels cramped.", routeSteps: ["Stand where the view feels least blocked.", "Let your eyes rest on the farthest line.", "Breathe out longer than you breathe in.", "Choose one thought to make smaller."]),
        SpiritTrail(mood: .reflective, title: "Maple Shadow Walk", place: "Ottawa River Leaf Path", minutes: 13, sound: .cedarForest, challenge: "Find a leaf shadow and trace it with your eyes.", storyTitle: "Metis River Roads", province: "Ontario", paletteSeed: 12, imageName: "TrailMapleShadow", difficulty: "Easy", season: "Autumn", summary: "A reflective urban-nature trail for noticing how leaves, rivers, and routes carry memory.", routeSteps: ["Find one leaf or branch shadow.", "Follow the edge without moving your head too much.", "Walk beside any line that suggests a river.", "End by naming what you want to carry forward."]),
        SpiritTrail(mood: .adventurous, title: "Atlantic Rock Pulse", place: "Bay of Fundy Stone Walk", minutes: 15, sound: .lakeShore, challenge: "Find three stones with different temperatures.", storyTitle: "Atlantic Tide Walk", province: "Nova Scotia", paletteSeed: 13, imageName: "TrailFundyRock", difficulty: "Medium", season: "Low tide mood", summary: "A tactile route inspired by huge tides, wet stone, and the feeling of movement under your feet.", routeSteps: ["Touch no unsafe surfaces; choose accessible stone, wall, or pavement.", "Compare three temperatures with your fingertips.", "Imagine the tide moving through the scene.", "Take a photo of the strongest line."]),
        SpiritTrail(mood: .focused, title: "Arctic Signal Path", place: "Nunavut Snowlight Track", minutes: 12, sound: .northernNight, challenge: "Find the brightest small point in your view.", storyTitle: "Inuit Northern Routes", province: "Nunavut", paletteSeed: 14, imageName: "TrailArcticSignal", difficulty: "Medium", season: "Winter mood", summary: "A crisp focus trail for finding one signal inside a visually quiet world.", routeSteps: ["Look for the smallest bright point.", "Walk toward it only if safe, otherwise hold it in view.", "Let every other detail become background.", "Finish by writing the signal in three words."]),
        SpiritTrail(mood: .calm, title: "Misty Hemlock Minute", place: "Vancouver Island Rain Edge", minutes: 6, sound: .rainForest, challenge: "Find one sound that repeats naturally.", storyTitle: "Coastal Rainforest Memory", province: "British Columbia", paletteSeed: 15, imageName: "TrailMistyHemlock", difficulty: "Easy", season: "Mist and rain", summary: "A tiny calming route where repeating sounds become a soft anchor.", routeSteps: ["Stand still for the first full minute.", "Identify one repeating sound.", "Walk only when you can keep hearing it.", "Let the repetition decide when you stop."]),
        SpiritTrail(mood: .social, title: "Market Maple Loop", place: "Montreal Park Lantern Walk", minutes: 9, sound: .cedarForest, challenge: "Notice a color someone else might love.", storyTitle: "Metis River Roads", province: "Quebec", paletteSeed: 16, imageName: "TrailMontrealLantern", difficulty: "Easy", season: "City evenings", summary: "A city-nature social trail for sharing color, street trees, and small observations.", routeSteps: ["Walk near light, trees, or window reflections.", "Pick a color that feels like someone you know.", "Send them the color name only.", "Save the scene in your collection mentally."]),
        SpiritTrail(mood: .reflective, title: "Polar Quiet Trail", place: "Churchill Snow Edge", minutes: 10, sound: .northernNight, challenge: "Find a boundary between two worlds.", storyTitle: "Polar Bear Edge", province: "Manitoba", paletteSeed: 17, imageName: "TrailPolarQuiet", difficulty: "Medium", season: "Cold days", summary: "A reflective edge-walk about thresholds: snow and road, light and dark, inside and outside.", routeSteps: ["Find a visible boundary.", "Walk beside it for as long as feels calm.", "Notice which side pulls your attention.", "Ask what boundary you need today."]),
        SpiritTrail(mood: .adventurous, title: "Ghost Town Glow", place: "Cariboo Lantern Street", minutes: 14, sound: .mountainWind, challenge: "Find something that looks abandoned but beautiful.", storyTitle: "Ghost Town Glow", province: "British Columbia", paletteSeed: 18, imageName: "TrailGhostTown", difficulty: "Medium", season: "Golden hour", summary: "A cinematic micro-adventure inspired by old mining streets, weathered boards, and neon memory.", routeSteps: ["Look for age: rust, worn paint, old signs, patched surfaces.", "Keep it respectful and do not trespass.", "Frame the object like a movie still.", "Write a three-word title for it."]),
        SpiritTrail(mood: .focused, title: "Beaver Dam Logic", place: "Algonquin Waterline Task", minutes: 11, sound: .lakeShore, challenge: "Find evidence of something built layer by layer.", storyTitle: "Beaver Builders", province: "Ontario", paletteSeed: 19, imageName: "TrailBeaverDam", difficulty: "Easy", season: "Spring", summary: "A practical focus trail about structure, small pieces, and patient building.", routeSteps: ["Find something layered: branches, bricks, clouds, shelves, waves.", "Count three layers.", "Choose one task that can be layered today.", "Define the first layer only."]),
        SpiritTrail(mood: .calm, title: "Northern Window Rest", place: "Aurora Glass Reflection", minutes: 5, sound: .northernNight, challenge: "Find a quiet light and let it stay still.", storyTitle: "Inuit Northern Routes", province: "Northern Canada", paletteSeed: 20, imageName: "TrailNorthernWindow", difficulty: "Easy", season: "Night", summary: "A no-pressure route for days when you only have a window, a light, and five minutes.", routeSteps: ["Sit or stand near a window.", "Find one stable light.", "Do not chase thoughts for five minutes.", "Save the feeling, not the image."]),
        SpiritTrail(mood: .focused, title: "Glacier Line Focus", place: "Athabasca Icefield Edge", minutes: 12, sound: .mountainWind, challenge: "Find a line that looks older than the surface around it.", storyTitle: "Jasper Night Sky", province: "Alberta", paletteSeed: 21, imageName: "TrailGlacierLine", difficulty: "Medium", season: "Cold clear days", summary: "A precise route for using icefield geometry as a mental sorting tool.", routeSteps: ["Start by choosing one visible edge: roofline, sidewalk, ridge, cloud, or snow line.", "Walk parallel to that edge for three minutes.", "Pause and name what feels fixed versus what feels temporary.", "Continue until you find a second edge crossing the first.", "Use the crossing point to choose one priority for the next hour."]),
        SpiritTrail(mood: .adventurous, title: "Sea Stack Spark", place: "Hopewell Rocks Tide Route", minutes: 15, sound: .lakeShore, challenge: "Find a tall shape and a low shape in the same view.", storyTitle: "Atlantic Tide Walk", province: "New Brunswick", paletteSeed: 22, imageName: "TrailHopewellStacks", difficulty: "Medium", season: "Low tide mood", summary: "A playful Atlantic route inspired by sea stacks, tide floors, and scale shifts.", routeSteps: ["Begin with your gaze low, scanning ground texture for twenty steps.", "Lift your view and find the tallest shape nearby.", "Walk a gentle arc so both tall and low shapes remain in memory.", "Take one photo or mental snapshot that includes both scales.", "End by naming what feels bigger now than when you started."]),
        SpiritTrail(mood: .reflective, title: "Red Sand Memory", place: "Prince Edward Island Dune Walk", minutes: 9, sound: .lakeShore, challenge: "Find a warm color and connect it to a memory.", storyTitle: "Atlantic Tide Walk", province: "Prince Edward Island", paletteSeed: 23, imageName: "TrailRedSand", difficulty: "Easy", season: "Warm wind", summary: "A soft reflective route built around red sand, low dunes, and remembered color.", routeSteps: ["Walk slowly until you find a warm color: red, amber, peach, gold, or rust.", "Hold the color in view for ten breaths.", "Let one memory arrive without forcing it.", "Walk for two more minutes carrying only the color, not the whole story.", "Finish by giving the memory a short title."]),
        SpiritTrail(mood: .social, title: "Harbour Signal Walk", place: "Halifax Boardwalk Glow", minutes: 8, sound: .campfire, challenge: "Share one small route recommendation with someone.", storyTitle: "Old Railways", province: "Nova Scotia", paletteSeed: 24, imageName: "TrailHalifaxHarbour", difficulty: "Easy", season: "Evening lights", summary: "A bright social route for turning a city-water walk into a small invitation.", routeSteps: ["Start near any edge that suggests water, glass, or movement.", "Walk until you notice a light repeating on a surface.", "Choose one person who would like this route.", "Send them a simple note: 'This made me think of you.'", "End by saving the route as a place worth returning to."]),
        SpiritTrail(mood: .calm, title: "Moraine Blue Pause", place: "Valley of the Ten Peaks", minutes: 7, sound: .lakeShore, challenge: "Find the calmest blue or dark surface around you.", storyTitle: "A Lake Held by Mountains", province: "Banff", paletteSeed: 25, imageName: "TrailMoraineBlue", difficulty: "Easy", season: "Still mornings", summary: "A short lake-color route for cooling down a busy mind.", routeSteps: ["Find the calmest blue, gray, black, or shadowed surface in view.", "Walk toward it if safe; otherwise keep it as your anchor.", "Let your shoulders drop each time your eyes return to it.", "Pause after five minutes and listen for the quietest sound.", "Complete the route by naming one thing you can leave untouched."]),
        SpiritTrail(mood: .focused, title: "Canyon Echo Task", place: "Maligne Canyon Sound Path", minutes: 13, sound: .mountainWind, challenge: "Find a repeating sound and turn it into a count.", storyTitle: "Jasper Night Sky", province: "Jasper", paletteSeed: 26, imageName: "TrailMaligneCanyon", difficulty: "Medium", season: "Running water", summary: "A focus route that converts echo, repetition, and narrow space into momentum.", routeSteps: ["Stand still until you identify one repeating sound.", "Count ten repetitions without checking the time.", "Walk for two minutes and keep the count in the background.", "Choose one task and break it into ten tiny repeats.", "End when you can name the first repeat clearly."]),
        SpiritTrail(mood: .adventurous, title: "Lighthouse Wind Route", place: "Peggy's Cove Granite Loop", minutes: 12, sound: .mountainWind, challenge: "Find a safe stone-like texture and trace its direction.", storyTitle: "Atlantic Tide Walk", province: "Nova Scotia", paletteSeed: 27, imageName: "TrailLighthouseWind", difficulty: "Medium", season: "Windy days", summary: "A coastal adventure route with granite energy, bright wind, and careful movement.", routeSteps: ["Start with both feet steady and choose a safe walking surface.", "Find a stone-like texture: rock, wall, pavement, step, or sculpture.", "Trace the strongest line in that texture with your eyes.", "Walk in the same direction for one minute if safe.", "Finish by turning back and noticing what the wind changed."]),
        SpiritTrail(mood: .reflective, title: "Old Growth Circle", place: "Cathedral Grove Cedar Ring", minutes: 14, sound: .cedarForest, challenge: "Find a natural ring, knot, or circular shape.", storyTitle: "Coastal Rainforest Memory", province: "British Columbia", paletteSeed: 28, imageName: "TrailOldGrowthCircle", difficulty: "Easy", season: "Forest shade", summary: "A reflective forest route about age, rings, and returning to the center.", routeSteps: ["Begin by slowing your pace before you enter the greenest area available.", "Look for a circle: knot, ring, puddle, stone, leaf curl, or lamp halo.", "Walk a small loop while keeping that circle in memory.", "Ask what pattern keeps repeating in your day.", "Close the route by choosing one repetition to soften."]),
        SpiritTrail(mood: .calm, title: "Snow Lantern Rest", place: "Quebec Winter Street", minutes: 6, sound: .northernNight, challenge: "Find one light softened by glass, mist, snow, or distance.", storyTitle: "Northern Window Rest", province: "Quebec", paletteSeed: 29, imageName: "TrailSnowLantern", difficulty: "Easy", season: "Winter evenings", summary: "A quiet city-winter route for finding calm through softened light.", routeSteps: ["Find a light that is not harsh: window, lamp, reflection, or sign.", "Let your gaze rest beside it, not directly inside it.", "Walk slowly for three minutes while returning to that softness.", "Pause and relax your jaw.", "Complete the route by saving the softest detail."]),
        SpiritTrail(mood: .social, title: "Maple Market Signal", place: "Toronto Ravine Morning", minutes: 10, sound: .cedarForest, challenge: "Recommend one nearby green place to someone.", storyTitle: "Montreal Lantern Trees", province: "Ontario", paletteSeed: 30, imageName: "TrailTorontoRavine", difficulty: "Easy", season: "Morning", summary: "A practical social route connecting city ravines, everyday trees, and shared local knowledge.", routeSteps: ["Start near a tree, park edge, planter, or green corridor.", "Walk until you find a place someone else could easily reach.", "Notice what makes it welcoming: shade, bench, sound, color, or quiet.", "Send the place name or description to someone.", "End by choosing when you might return."]),
        SpiritTrail(mood: .focused, title: "Tundra Marker Path", place: "Nunavut Stone Inukshuk Line", minutes: 11, sound: .northernNight, challenge: "Find three markers that could guide a traveler.", storyTitle: "Inuit Northern Routes", province: "Nunavut", paletteSeed: 31, imageName: "TrailTundraMarker", difficulty: "Medium", season: "Open cold", summary: "A minimal focus route about markers, direction, and choosing the next visible point.", routeSteps: ["Look for the first marker: sign, post, tree, stone, lamp, doorway, or bright object.", "Walk to a safe point where you can see a second marker.", "Find a third marker and imagine a route between all three.", "Choose the marker that feels most useful.", "Let that marker represent your next action."]),
        SpiritTrail(mood: .adventurous, title: "Canoe Portage Pulse", place: "Algonquin Carry Trail", minutes: 15, sound: .cedarForest, challenge: "Find something that would be worth carrying carefully.", storyTitle: "Beaver Builders", province: "Ontario", paletteSeed: 32, imageName: "TrailCanoePortage", difficulty: "Medium", season: "Summer forest", summary: "A movement-rich route inspired by portage paths, effort, and careful carrying.", routeSteps: ["Begin by naming what you are carrying today, literally or mentally.", "Walk for five minutes while imagining it has weight.", "Find an object or detail that seems worth protecting.", "Pause and decide what can be set down.", "Finish with lighter steps for the final minute."]),
        SpiritTrail(mood: .reflective, title: "Northern Rail Memory", place: "White Pass Echo Track", minutes: 12, sound: .mountainWind, challenge: "Find two parallel lines and follow them with your eyes.", storyTitle: "Old Railways", province: "Yukon", paletteSeed: 33, imageName: "TrailWhitePassRail", difficulty: "Easy", season: "Clear air", summary: "A reflective rail-inspired route about parallel choices and where they might lead.", routeSteps: ["Find two parallel lines: path edges, rails, shadows, boards, wires, or seams.", "Stand still and follow them into the distance.", "Walk beside them or imagine walking beside them for three minutes.", "Ask what two choices are running side by side in your life.", "End by naming which line needs attention first."]),
        SpiritTrail(mood: .calm, title: "Island Rain Porch", place: "Tofino Soft Weather Route", minutes: 8, sound: .rainForest, challenge: "Find one place where rain would sound gentle.", storyTitle: "Coastal Rainforest Memory", province: "British Columbia", paletteSeed: 34, imageName: "TrailTofinoRain", difficulty: "Easy", season: "Rain", summary: "A cozy calm route for rainy days, covered paths, porches, windows, and soft weather.", routeSteps: ["Start under cover or imagine the nearest shelter.", "Find a surface where rain would sound gentle.", "Listen to Rain Forest sound and match it to that surface.", "Walk only as far as comfort allows.", "Finish by choosing one thing you do not need to hurry."]),
        SpiritTrail(mood: .social, title: "Festival Tree Walk", place: "Winnipeg River Lights", minutes: 9, sound: .campfire, challenge: "Ask someone which season they miss most.", storyTitle: "Metis River Roads", province: "Manitoba", paletteSeed: 35, imageName: "TrailWinnipegLights", difficulty: "Easy", season: "Festival nights", summary: "A warm social route about seasons, lights, and small questions that open memory.", routeSteps: ["Walk near a light source, tree line, or river-like path.", "Think of the season you miss most today.", "Ask someone their season or write the question down.", "Notice whether their answer changes your view.", "End by saving both seasons as a tiny collection."]),
        SpiritTrail(mood: .focused, title: "Raven Ridge Choice", place: "Haida Gwaii Forest Edge", minutes: 13, sound: .cedarForest, challenge: "Find a fork, split, or branching shape.", storyTitle: "Coastal Rainforest Memory", province: "British Columbia", paletteSeed: 36, imageName: "TrailRavenRidge", difficulty: "Medium", season: "Forest mist", summary: "A choice-making route that uses branches and forks as a clean decision frame.", routeSteps: ["Look for a branch, split path, Y-shape, or divided shadow.", "Stand where both directions are visible.", "Name what each side could represent.", "Walk toward the side that feels simpler, not louder.", "Finish by writing the decision as one verb."]),
        SpiritTrail(mood: .adventurous, title: "Badlands Neon Drop", place: "Drumheller Hoodoo Walk", minutes: 14, sound: .mountainWind, challenge: "Find a shape that looks carved by time.", storyTitle: "Yoho Stone Stories", province: "Alberta", paletteSeed: 37, imageName: "TrailBadlandsDrop", difficulty: "Medium", season: "Dry heat", summary: "A bright, strange route inspired by hoodoos, dry valleys, and ancient layers.", routeSteps: ["Start by scanning for layered or eroded shapes.", "Walk in a gentle zigzag rather than a straight line.", "Find one surface that looks carved, worn, or weathered.", "Imagine what removed material from it: wind, water, time, pressure.", "End by naming what pressure you can release."]),
        SpiritTrail(mood: .reflective, title: "Orchard Evening Route", place: "Okanagan Glow Path", minutes: 10, sound: .lakeShore, challenge: "Find a repeating natural pattern in rows, waves, or branches.", storyTitle: "Metis River Roads", province: "British Columbia", paletteSeed: 38, imageName: "TrailOkanaganOrchard", difficulty: "Easy", season: "Late summer", summary: "A golden reflective route about rows, repetition, and the comfort of ordered nature.", routeSteps: ["Find a repeated pattern: trees, windows, fence posts, waves, tiles, or branches.", "Walk beside the pattern for three minutes.", "Notice where the pattern breaks.", "Ask where your routine needs a small break.", "Complete the route by choosing one gentle change."]),
        SpiritTrail(mood: .calm, title: "Fog Bell Breath", place: "Newfoundland Cliff Morning", minutes: 7, sound: .mountainWind, challenge: "Find the softest edge in your view.", storyTitle: "Atlantic Tide Walk", province: "Newfoundland", paletteSeed: 39, imageName: "TrailFogBell", difficulty: "Easy", season: "Fog", summary: "A calm coastal route for soft edges, low visibility, and breathing with uncertainty.", routeSteps: ["Look for an edge that is blurred by distance, shadow, fog, glass, or light.", "Let your eyes rest there instead of trying to sharpen it.", "Walk for two minutes with a slower exhale.", "Find a second soft edge.", "End by accepting one thing that does not need clarity yet."]),
        SpiritTrail(mood: .social, title: "Neighbourhood Nature Swap", place: "Local Maple-to-Pine Loop", minutes: 6, sound: .cedarForest, challenge: "Trade one nature detail with someone.", storyTitle: "Northern Window Rest", province: "Home Mode", paletteSeed: 40, imageName: "TrailNatureSwap", difficulty: "Easy", season: "Any day", summary: "A tiny social route that works anywhere: one detail found, one detail shared.", routeSteps: ["Find one nature detail within two minutes: leaf, sky, bird sound, water, plant, or light.", "Describe it in five words or less.", "Ask someone to send or name one detail back.", "Compare both without ranking them.", "Finish by saving the exchange as today's social trail."])
    ]

    static let stories: [CanadaStory] = [
        CanadaStory(category: "National Parks", title: "Banff National Park", region: "Alberta", readTime: "3 min read", audioTime: "90 sec audio", body: "Canada's first national park began around hot springs and grew into a mountain refuge of lakes, forests, glaciers, and quiet trails.", symbol: "leaf.fill", tintName: "pink", imageName: "StoryBanff", quote: "Banff is not only scenery. It is a practice in looking slowly.", paragraphs: ["Banff National Park is often remembered through turquoise lakes and sharp mountain silhouettes, but the quieter story is about attention. A short walk here can feel larger than its distance because every surface changes quickly: water, stone, cloud, forest, and snow.", "The park grew from a hot springs reserve into a protected mountain landscape. That history matters because WN SPRT treats nature as a reset, not a trophy. You are not trying to conquer a route; you are borrowing a few minutes of mountain rhythm.", "For a reflective trail, imagine Banff as a place that asks one question: what becomes clear when you stop rushing the view?"]),
        CanadaStory(category: "National Parks", title: "A Lake Held by Mountains", region: "Alberta", readTime: "2 min read", audioTime: "60 sec audio", body: "Lake Louise is famous for color, but its real mood is the feeling of being held between water, ice, and steep stone.", symbol: "drop.fill", tintName: "cyan", imageName: "StoryLakeLouise", quote: "A reflection is a landscape taking one slow breath.", paragraphs: ["Lake Louise is easy to recognize and hard to fully absorb. The water catches mountain light in a way that feels almost designed, yet its calmest power is repetition: shore, reflection, ripple, shore again.", "A micro-trail around this mood does not need distance. It needs patience. Watch one reflected shape for thirty seconds and you will see that stillness is never actually still.", "That is the point of the Calm Trail: let a stable view show you tiny movement until your own thoughts loosen."]),
        CanadaStory(category: "National Parks", title: "Jasper Night Sky", region: "Alberta", readTime: "3 min read", audioTime: "90 sec audio", body: "Jasper is known for vast dark skies. On clear nights, the stars feel close enough to become part of the trail.", symbol: "moon.stars.fill", tintName: "cyan", imageName: "StoryJasper", quote: "The night sky makes room for thoughts that daylight crowds out.", paragraphs: ["Jasper's night sky identity is rooted in darkness as a kind of landscape. When artificial light drops away, the overhead world becomes textured and directional.", "For WN SPRT, Jasper is the focused mood in its cleanest form. A dark sky reduces clutter. It gives you fewer things to look at, but each one matters more.", "The Jasper Compass Loop borrows that feeling: choose a line, follow it gently, and let one signal become stronger than the noise."]),
        CanadaStory(category: "National Parks", title: "Yoho Stone Stories", region: "British Columbia", readTime: "3 min read", audioTime: "90 sec audio", body: "Yoho carries waterfalls, fossil beds, and old mountain paths where deep time sits close to the surface.", symbol: "mountain.2.fill", tintName: "orange", imageName: "StoryYoho", quote: "Stone is slow, but it is never empty.", paragraphs: ["Yoho's name is often associated with awe, and the landscape earns it: water drops hard, stone rises fast, and old layers reveal that mountains are not simple objects.", "A short WN SPRT route inspired by Yoho uses contrast. Hard stone and soft moss. Fast water and slow rock. Bright lichen and deep shadow.", "When your attention compares edges, decisions become easier. You can ask: what in my day needs softness, and what needs structure?"]),
        CanadaStory(category: "Indigenous Heritage", title: "Cree Star Knowledge", region: "Prairies and North", readTime: "3 min read", audioTime: "90 sec audio", body: "Cree sky stories connect seasons, movement, and memory, reminding travelers that navigation can be cultural as well as practical.", symbol: "sparkles", tintName: "lime", imageName: "StoryCreeStars", quote: "A sky can be a calendar, a route, and a story at once.", paragraphs: ["Across many Indigenous knowledge systems, the sky is not a distant decoration. It is connected to season, travel, teaching, and memory. Cree star knowledge is part of that broader relationship between observation and life on the land.", "WN SPRT approaches this with respect and restraint. A micro-trail cannot replace cultural learning, but it can remind a user that looking up is a form of listening.", "The Prairie Sky Reset uses open space as a mental clearing. You are invited to notice the widest shape around you, then let one crowded thought become smaller."]),
        CanadaStory(category: "Indigenous Heritage", title: "Inuit Northern Routes", region: "Arctic", readTime: "3 min read", audioTime: "90 sec audio", body: "Inuit knowledge reads snow, wind, coastlines, and animals as living maps shaped by generations of observation.", symbol: "wind", tintName: "cyan", imageName: "StoryInuitRoutes", quote: "A route is not only where you go. It is what you know how to notice.", paragraphs: ["Northern travel depends on reading signs that may look subtle to outsiders: snow texture, wind direction, ice behavior, animal movement, and coastline memory.", "That kind of attention is deep expertise. In WN SPRT, northern-inspired trails are not about imitation; they are about humility. They invite the user to notice one signal with care.", "The Arctic Signal Path asks for the brightest small point in view. It is a simple exercise, but it honors a larger truth: survival and calm both begin with attention."]),
        CanadaStory(category: "Indigenous Heritage", title: "Metis River Roads", region: "Central Canada", readTime: "3 min read", audioTime: "90 sec audio", body: "Metis communities helped shape trade routes, river travel, music, craft, and a distinct culture of movement.", symbol: "water.waves", tintName: "pink", imageName: "StoryMetisRiver", quote: "Rivers remember movement even when the traveler is gone.", paragraphs: ["Rivers shaped travel, trade, and community across much of Canada. Metis history is deeply connected with movement through these corridors, along with craft, language, music, and exchange.", "A WN SPRT river trail is about carrying. What do you bring forward? What do you leave on the bank? Even a city path can become a river road if you follow a line with intention.", "The Maple Shadow Walk uses leaf-shadow and route-memory to turn an ordinary walk into a small act of reflection."]),
        CanadaStory(category: "Wildlife", title: "Moose at Dusk", region: "Boreal Forest", readTime: "2 min read", audioTime: "60 sec audio", body: "A moose can move through wetland shadows with surprising quiet. Seeing one is a lesson in scale and patience.", symbol: "eye.fill", tintName: "orange", imageName: "StoryMoose", quote: "The largest presence can still arrive quietly.", paragraphs: ["Moose are large enough to change a scene immediately, yet their movement can be startlingly quiet. Wetlands, forest edges, and dusk light suit them.", "The WN SPRT lesson is not to seek wildlife directly. It is to borrow the patience wildlife asks of us: soften your movement, widen your attention, and let the world appear without forcing it.", "That patience turns a short trail into a better kind of observation."]),
        CanadaStory(category: "Wildlife", title: "Beaver Builders", region: "Across Canada", readTime: "3 min read", audioTime: "90 sec audio", body: "Beavers alter water, shorelines, and habitats. Their work turns small streams into whole neighborhoods for life.", symbol: "hammer.fill", tintName: "lime", imageName: "StoryBeaver", quote: "Layer by layer is how a small act becomes a landscape.", paragraphs: ["Beavers are famous builders, but the most interesting part is the effect of building. A dam changes water. Changed water changes plants. Changed plants change who can live nearby.", "This is why the Beaver Dam Logic trail is a focus route. It asks you to find something layered and choose the first layer of a task. Not the whole project. Not the grand plan. Just the first placed branch.", "Nature often works through accumulation. So can attention."]),
        CanadaStory(category: "Wildlife", title: "Polar Bear Edge", region: "Northern Canada", readTime: "3 min read", audioTime: "90 sec audio", body: "Polar bears live at the meeting point of ice, sea, and weather. Their world changes with every season.", symbol: "snowflake", tintName: "cyan", imageName: "StoryPolar", quote: "Edges are where a landscape tells the truth.", paragraphs: ["Polar bear habitat is an edge-world: ice and water, cold and hunger, distance and patience. The image is powerful because the environment is powerful.", "WN SPRT uses the idea of an edge carefully. The Polar Quiet Trail asks users to find a boundary in their own safe surroundings: light and dark, wall and path, road and grass.", "A boundary can clarify a mood. Sometimes what you need is not more energy, but a cleaner edge."]),
        CanadaStory(category: "Hidden Canada", title: "Ghost Town Glow", region: "British Columbia", readTime: "3 min read", audioTime: "90 sec audio", body: "Old mining towns still hold boardwalks, tools, and stories of sudden hope beneath mountain weather.", symbol: "building.columns.fill", tintName: "pink", imageName: "StoryGhostTown", quote: "Abandoned does not always mean empty.", paragraphs: ["Ghost towns compress time. A boardwalk, a rusted tool, a faded wall: each one suggests a rush of hope that eventually moved elsewhere.", "For a micro-adventure, this becomes a visual practice. Find something worn but beautiful. Do not enter unsafe spaces. Do not treat history like a prop. Just notice the glow that remains when use has ended.", "The Ghost Town Glow trail is cinematic because memory often is."]),
        CanadaStory(category: "Hidden Canada", title: "Remote Lake Signal", region: "Yukon", readTime: "2 min read", audioTime: "60 sec audio", body: "Some northern lakes feel untouched because reaching them requires time, respect, and a willingness to listen first.", symbol: "dot.radiowaves.left.and.right", tintName: "blue", imageName: "StoryRemoteLake", quote: "Distance can make a small sound feel important.", paragraphs: ["A remote lake is not only a place on a map. It is a mood: less interruption, more sky, and the feeling that signals must travel farther.", "The Remote Lake Signal trail translates that mood for everyday life. Any reflection can become a lake if you let it break apart and reform while you move.", "The challenge is simple: find a reflection that changes. The result is bigger than the task."]),
        CanadaStory(category: "Hidden Canada", title: "Old Railways", region: "Atlantic Canada", readTime: "3 min read", audioTime: "90 sec audio", body: "Disused rail lines have become quiet corridors where towns, forests, and shoreline histories meet.", symbol: "tram.fill", tintName: "orange", imageName: "StoryRailways", quote: "A line once built for distance can become a place for returning.", paragraphs: ["Old rail corridors have a special calm because they were engineered for movement. Even after trains are gone, the route still suggests direction.", "Many communities have turned old rail lines into walking and cycling paths. The result is a soft overlap of utility, memory, and everyday nature.", "WN SPRT uses this as a reflective structure: walk a line, notice what is behind you, and choose what is ahead."]),
        CanadaStory(category: "Hidden Canada", title: "Atlantic Tide Walk", region: "Nova Scotia", readTime: "2 min read", audioTime: "60 sec audio", body: "Atlantic shorelines can make time visible through stone, weed, water marks, and the changing height of the sea.", symbol: "water.waves", tintName: "cyan", imageName: "StoryAtlanticTide", quote: "The tide is a clock you can feel under your feet.", paragraphs: ["On tidal coasts, change does not need a metaphor. It is visible. Wet lines climb and fall. Rocks warm and cool. Seaweed marks where water has recently been.", "The Atlantic Rock Pulse trail turns that into a tactile reset. Three stones, three temperatures, one body remembering that time is physical.", "A short walk can become a tide table for the mood."]),
        CanadaStory(category: "City Nature", title: "Montreal Lantern Trees", region: "Quebec", readTime: "2 min read", audioTime: "60 sec audio", body: "City parks at night can feel like small theatres where leaves, windows, and streetlights perform together.", symbol: "lantern.fill", tintName: "pink", imageName: "StoryMontreal", quote: "A city tree still knows how to hold light.", paragraphs: ["Not every forest moment requires wilderness. In Canadian cities, street trees, parks, rivers, and winter light create their own nature language.", "The Market Maple Loop is a social trail because city color is shareable. You can notice a lantern, a leaf, a window glow, and send the color to someone without explaining too much.", "It keeps the app premium but practical: nature can enter the day where the day already is."]),
        CanadaStory(category: "City Nature", title: "Northern Window Rest", region: "Home Mode", readTime: "1 min read", audioTime: "30 sec audio", body: "When weather, time, or energy keeps you inside, a window can still become a tiny northern lights mode.", symbol: "rectangle.on.rectangle", tintName: "lime", imageName: "StoryWindow", quote: "A quiet light is enough for a reset.", paragraphs: ["WN SPRT is not a hiking app, and this matters most on hard days. You do not need a trailhead. You need a moment that feels intentionally held.", "The Northern Window Rest asks for a quiet light and five minutes. That is all. The premium feeling comes from respecting a small ritual instead of apologizing for it.", "Sometimes the smallest route is the one you actually complete."])
    ]

    static let badges: [SpiritBadge] = [
        SpiritBadge(title: "Maple Explorer", requirement: "Complete 5 trails", icon: "leaf.fill", tintName: "pink", threshold: 5),
        SpiritBadge(title: "Forest Walker", requirement: "Complete 10 trails", icon: "tree.fill", tintName: "lime", threshold: 10),
        SpiritBadge(title: "Mountain Spirit", requirement: "Complete 20 trails", icon: "mountain.2.fill", tintName: "cyan", threshold: 20),
        SpiritBadge(title: "Wildlife Observer", requirement: "Complete 10 challenges", icon: "pawprint.fill", tintName: "orange", threshold: 10),
        SpiritBadge(title: "Aurora Keeper", requirement: "Save 7 quotes", icon: "moon.stars.fill", tintName: "blue", threshold: 7),
        SpiritBadge(title: "Story Listener", requirement: "Open 12 stories", icon: "book.closed.fill", tintName: "pink", threshold: 12),
        SpiritBadge(title: "Lake Listener", requirement: "Play 8 sound sessions", icon: "waveform", tintName: "cyan", threshold: 8),
        SpiritBadge(title: "Hidden Canada", requirement: "Open 5 hidden stories", icon: "sparkles", tintName: "orange", threshold: 5),
        SpiritBadge(title: "Prairie Breather", requirement: "Complete 3 calm trails", icon: "wind", tintName: "lime", threshold: 3)
    ]

    static let provinces: [SpiritProvince] = [
        SpiritProvince(name: "Banff", unlockAt: 0, stories: ["Banff National Park", "A Lake Held by Mountains"], symbol: "leaf.fill"),
        SpiritProvince(name: "Jasper", unlockAt: 3, stories: ["Jasper Night Sky", "Moose at Dusk"], symbol: "moon.stars.fill"),
        SpiritProvince(name: "Yukon", unlockAt: 6, stories: ["Gold Trails and Night Skies", "Remote Lake Signal"], symbol: "sparkles"),
        SpiritProvince(name: "British Columbia", unlockAt: 9, stories: ["Yoho Stone Stories", "Coastal Rainforest Memory"], symbol: "tree.fill"),
        SpiritProvince(name: "Nova Scotia", unlockAt: 12, stories: ["Old Railways", "Atlantic Tide Walk"], symbol: "water.waves"),
        SpiritProvince(name: "Nunavut", unlockAt: 16, stories: ["Inuit Northern Routes", "Arctic Signal Path"], symbol: "snowflake"),
        SpiritProvince(name: "Quebec", unlockAt: 18, stories: ["Montreal Lantern Trees", "Metis River Roads"], symbol: "lantern.fill")
    ]

    static let quotes = [
        "The forest knows things we have forgotten.",
        "A small trail can still change the weather inside you.",
        "Listen long enough and the lake becomes a mirror.",
        "The north does not rush, and neither do you.",
        "Every bright step is a way back to yourself.",
        "A quiet light is enough for a reset.",
        "Layer by layer is how attention becomes a place."
    ]

    static let weeklyQuest = SpiritQuest(title: "Complete 5 reflective trails", target: 5, reward: "New neon badge")
}
